# Generated by Django 3.2 on 2021-09-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0002_auto_20210907_1609'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table=None,
        ),
    ]
