# Generated by Django 3.1.7 on 2021-09-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0009_auto_20210913_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(error_messages={'unique': 'Пользователь с таким Email уже существует.'}, help_text='', max_length=150, unique=True, verbose_name='username'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username',)},
        ),
    ]
