# Generated by Django 3.2 on 2021-09-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0010_auto_20210910_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Роль',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(error_messages={'unique': 'Пользователь с таким Email уже существует.'}, help_text='', max_length=150, unique=True, verbose_name='Email'),
        ),
    ]
