# Generated by Django 3.2 on 2021-09-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0017_auto_20210917_1303'),
        ('userControl', '0017_auto_20210917_1336'),
    ]

    operations = [
    ]
