# Generated by Django 3.2.7 on 2021-09-01 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Researh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип исследования')),
                ('type_request', models.CharField(max_length=50, verbose_name='Тип заявки')),
                ('identityCode', models.CharField(max_length=50, verbose_name='Код исследования')),
                ('date_accepted', models.DateField(verbose_name='Дата одобрения')),
                ('date_created', models.DateField(verbose_name='Дата загрузки в систему')),
                ('version', models.CharField(max_length=50, verbose_name='Версия исследования')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер протокола')),
                ('protocol_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название протокола')),
                ('work_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название работы')),
                ('division', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подразделение')),
                ('executor', models.CharField(blank=True, max_length=500, null=True, verbose_name='Исполнитель')),
                ('specialization', models.CharField(blank=True, max_length=500, null=True, verbose_name='Специализация')),
                ('managers', models.CharField(blank=True, max_length=500, null=True, verbose_name='Менеджеры')),
                ('name_research', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название исследования')),
                ('drug_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название препарата')),
                ('research_center', models.CharField(blank=True, max_length=500, null=True, verbose_name='Исследовательский центр')),
                ('customer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заказчик')),
                ('customer_contacts', models.CharField(blank=True, max_length=500, null=True, verbose_name='Контактные данные заказчика')),
                ('duration', models.DateField(blank=True, null=True, verbose_name='Дата окончания исследования')),
                ('main_researcher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_researcher_id', to=settings.AUTH_USER_MODEL)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_research_id', to='researchManager.researh')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название документа')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Версия документа')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('file', models.CharField(max_length=250, verbose_name='Путь к файлу')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_id', to='researchManager.researh')),
            ],
        ),
    ]
