# Generated by Django 3.1.7 on 2021-09-15 10:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип исследования')),
                ('type_request', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип заявки')),
                ('owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='ОВНЕР')),
                ('identityCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код исследования')),
                ('date_accepted', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата одобрения')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата загрузки в систему')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Версия исследования')),
                ('protocol_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер протокола')),
                ('protocol_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название протокола')),
                ('work_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название работы')),
                ('division', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подразделение')),
                ('executor', models.CharField(blank=True, max_length=500, null=True, verbose_name='Исполнитель')),
                ('specialization', models.CharField(blank=True, max_length=500, null=True, verbose_name='Специализация')),
                ('managers', models.CharField(blank=True, max_length=500, null=True, verbose_name='Менеджеры')),
                ('name_research', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название исследования')),
                ('drug_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название препарата')),
                ('main_researcher', models.CharField(blank=True, max_length=500, null=True, verbose_name='Главвный исследователь')),
                ('research_center', models.CharField(blank=True, max_length=500, null=True, verbose_name='Исследовательский центр')),
                ('customer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заказчик')),
                ('customer_contacts', models.CharField(blank=True, max_length=500, null=True, verbose_name='Контактные данные заказчика')),
                ('duration', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания исследования')),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название документа')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Версия документа')),
                ('date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата документа')),
                ('file', models.FileField(upload_to='', verbose_name='Путь к файлу')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_id', to='researchManager.research')),
            ],
        ),
    ]
