# Generated by Django 3.1.7 on 2021-09-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='version',
        ),
        migrations.AlterField(
            model_name='research',
            name='date_accepted',
            field=models.DateField(blank=True, default='2021-05-05', null=True, verbose_name='Дата одобрения'),
        ),
    ]
