# Generated by Django 3.2.7 on 2021-09-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='researchs/%Y/<function user_directory_path at 0x000000FFAB64EEE0>', verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='information',
            name='main_researcher',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Главвный исследователь'),
        ),
    ]
