# Generated by Django 3.1.7 on 2021-10-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='duration',
            new_name='duration_string',
        ),
    ]
