# Generated by Django 3.2 on 2021-09-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchManager', '0001_initial'),
    ]

    operations = [
<<<<<<< HEAD
        migrations.RemoveField(
            model_name='research',
            name='version',
        ),
=======
>>>>>>> editNewVersion
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='research',
            name='date_accepted',
            field=models.DateField(blank=True, null=True, verbose_name='Дата одобрения'),
        ),
        migrations.AlterField(
            model_name='research',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
