# Generated by Django 3.1.7 on 2021-09-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchManager', '0002_auto_20210917_1336'),
        ('researchManager', '0002_auto_20210917_1303'),
    ]

    operations = [
    ]
