# Generated by Django 3.1.7 on 2021-10-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchManager', '0002_auto_20211005_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='duration_string',
            new_name='duration',
        ),
    ]
