# Generated by Django 3.2.7 on 2021-09-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchManager', '0002_auto_20210906_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='researchs/%Y/<function user_directory_path at 0x00000065908BEEE0>', verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='researh',
            name='date_accepted',
            field=models.DateTimeField(verbose_name='Дата одобрения'),
        ),
        migrations.AlterField(
            model_name='researh',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки в систему'),
        ),
    ]
