# Generated by Django 3.1.7 on 2021-09-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchManager', '0003_merge_20210920_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='version',
            field=models.IntegerField(blank=True, null=True, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='research',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='research',
            name='main_researcher',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Главный исследователь'),
        ),
    ]
