# Generated by Django 3.1.7 on 2021-09-21 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researchManager', '0004_auto_20210920_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userControl.user'),
            preserve_default=False,
        ),
    ]
