# Generated by Django 3.2.7 on 2021-09-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchManager', '0004_auto_20210906_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='researchs/%Y/<function user_directory_path at 0x000000F8EEE2EEE0>', verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='information',
            name='duration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания исследования'),
        ),
    ]
