# Generated by Django 3.2.7 on 2021-09-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchManager', '0005_auto_20210906_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата документа'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='researh',
            name='date_accepted',
            field=models.DateTimeField(blank=True, default='2021-05-25 11:17:49.353268', null=True, verbose_name='Дата одобрения'),
        ),
    ]
