# Generated by Django 3.2.7 on 2021-09-07 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchManager', '0006_auto_20210907_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_research_id', to='researchManager.researh'),
        ),
    ]
