# Generated by Django 3.1.7 on 2021-09-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchManager', '0007_research_acceptedonmeeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='acceptedOnMeeting',
        ),
        migrations.AddField(
            model_name='research',
            name='addedOnMeeting',
            field=models.BooleanField(default=False, verbose_name='Добавленно на заседании'),
        ),
    ]
