# Generated by Django 3.1.7 on 2021-10-05 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researchManager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата заседания')),
                ('time', models.TimeField(verbose_name='Время заседания')),
                ('subpoena', models.CharField(max_length=1000, verbose_name='Повестка')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingId', to='meetingManager.meeting')),
                ('researchsInMeeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researchId', to='researchManager.research')),
                ('usersInMeeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userInMeeting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
