# Generated by Django 3.1.7 on 2021-09-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='time',
            field=models.TimeField(default='17:00', verbose_name='Время заседания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заседания'),
        ),
    ]
