# Generated by Django 3.1.7 on 2021-09-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetingManager', '0002_auto_20210923_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingdata',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingId', to='meetingManager.meeting'),
        ),
    ]
