# Generated by Django 3.1.7 on 2021-09-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingManager', '0003_auto_20210923_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingdata',
            old_name='research',
            new_name='researchsInMeeting',
        ),
        migrations.RenameField(
            model_name='meetingdata',
            old_name='user',
            new_name='usersInMeeting',
        ),
    ]
