# Generated by Django 3.1.7 on 2021-09-23 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchManager', '0006_auto_20210921_1438'),
        ('meetingManager', '0005_auto_20210923_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingdata',
            name='researchsInMeeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researchId', to='researchManager.research'),
        ),
    ]
