# Generated by Django 3.1.7 on 2021-09-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingManager', '0007_auto_20210923_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='subpoena',
            field=models.CharField(default='tmp', max_length=1000, verbose_name='Повестка'),
            preserve_default=False,
        ),
    ]
